// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "63bd056e-a8b7-4c04-916f-e88bafbe78e6";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onHoldingRegister40001Change();
void onHoldingRegister40002Change();
void onDiscreate00001Change();
void onDiscreate00002Change();

int holdingRegister40001;
int holdingRegister40002;
bool discreate00001;
bool discreate00002;

#define RXD2 16 // GPIO16 = RX2
#define TXD2 17 // GPIO17 = TX2

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(holdingRegister40001, READWRITE, 5 * SECONDS, onHoldingRegister40001Change);
  ArduinoCloud.addProperty(holdingRegister40002, READWRITE, 5 * SECONDS, onHoldingRegister40002Change);
  ArduinoCloud.addProperty(discreate00001, READWRITE, 5 * SECONDS, onDiscreate00001Change);
  ArduinoCloud.addProperty(discreate00002, READWRITE, 5 * SECONDS, onDiscreate00002Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
